spring:
  application:
    name: franquicias-webflux
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://postgres:5432/franquicias}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20

server:
  port: 8080

logging:
  level:
    com.franquicias: DEBUG

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

